[package]
name = "sentiric-observer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
futures-util = "0.3"
bollard = "0.16"
axum = { version = "0.7", features = ["ws"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4"
anyhow = "1.0"

# --- gRPC STACK ---
tonic = "0.12"
prost = "0.13"

lazy_static = "1.4"
regex = "1.10"

[build-dependencies]
tonic-build = "0.12"