[package]
name = "sentiric-observer"
version = "1.3.0"
edition = "2021"

[dependencies]
# Async Runtime & Web Server
tokio = { version = "1.40", features = ["full"] }
futures-util = "0.3"
axum = { version = "0.7", features = ["ws"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }

# Infrastructure
bollard = "0.16"
pcap = "2.0.0"
etherparse = "0.13"

# Data & Logic
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
regex = "1.10"
lazy_static = "1.4"

# Observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tonic = "0.12"
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"